spring:
  application:
     name: telecom
  datasource:
    url: jdbc:mysql://192.168.0.252:3306/telecom?useUnicode=true&userSSL=false&characterEncoding=utf8&allowMultiQueries=true&netTimeoutForStreamingResults=0&serverTimezone=Australia/Melbourne
    username: codingTest
    password: codingTest1@3
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      connection-test-query: select 1
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
server:
  port: 18080